services:
  db:
    image: postgres:16
    container_name: zeiterfassung-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zeiterfassung
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./internal/db/migration/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/01-init_schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d zeiterfassung" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: zeiterfassung_backend
    restart: always
    environment:
      - APP_PORT=8080
      - APP_NAME=zeiterfassung
      - APP_DEBUG=false
      - DB_CONNECTION=postgres
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=zeiterfassung
      - DB_PORT=5432
      - MIGRATION_URL=file://internal/db/migration
      - JWT_SECRET=XhvFjfp4L5O8JND2
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zeiterfassung-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
