// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_entry.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO
    time_entries (
        submission_id,
        entry_date,
        start_time,
        end_time,
        break_min,
        duration_h,
        note
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, submission_id, entry_date, start_time, end_time, break_min, duration_h, note, created_at, updated_at
`

type CreateTimeEntryParams struct {
	SubmissionID uuid.UUID      `json:"submission_id"`
	EntryDate    pgtype.Date    `json:"entry_date"`
	StartTime    pgtype.Time    `json:"start_time"`
	EndTime      pgtype.Time    `json:"end_time"`
	BreakMin     pgtype.Int4    `json:"break_min"`
	DurationH    pgtype.Numeric `json:"duration_h"`
	Note         pgtype.Text    `json:"note"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.SubmissionID,
		arg.EntryDate,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMin,
		arg.DurationH,
		arg.Note,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMin,
		&i.DurationH,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWeeklySubmission = `-- name: CreateWeeklySubmission :one
INSERT INTO
    weekly_submissions (
        user_id,
        week_number,
        year,
        status
    )
VALUES ($1, $2, $3, 'offen')
RETURNING
    id, user_id, week_number, year, status, submitted_at, approved_at, processed_by, processed_at, created_at, updated_at
`

type CreateWeeklySubmissionParams struct {
	UserID     int64 `json:"user_id"`
	WeekNumber int32 `json:"week_number"`
	Year       int32 `json:"year"`
}

func (q *Queries) CreateWeeklySubmission(ctx context.Context, arg CreateWeeklySubmissionParams) (WeeklySubmission, error) {
	row := q.db.QueryRow(ctx, createWeeklySubmission, arg.UserID, arg.WeekNumber, arg.Year)
	var i WeeklySubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekNumber,
		&i.Year,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimeEntriesBySubmission = `-- name: DeleteTimeEntriesBySubmission :exec
DELETE FROM time_entries WHERE submission_id = $1
`

func (q *Queries) DeleteTimeEntriesBySubmission(ctx context.Context, submissionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeEntriesBySubmission, submissionID)
	return err
}

const getTimeEntriesBySubmission = `-- name: GetTimeEntriesBySubmission :many
SELECT id, submission_id, entry_date, start_time, end_time, break_min, duration_h, note, created_at, updated_at
FROM time_entries
WHERE
    submission_id = $1
ORDER BY entry_date
`

func (q *Queries) GetTimeEntriesBySubmission(ctx context.Context, submissionID uuid.UUID) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, getTimeEntriesBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeEntry{}
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.EntryDate,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMin,
			&i.DurationH,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklySubmission = `-- name: GetWeeklySubmission :one
SELECT id, user_id, week_number, year, status, submitted_at, approved_at, processed_by, processed_at, created_at, updated_at
FROM weekly_submissions
WHERE
    user_id = $1
    AND week_number = $2
    AND year = $3
LIMIT 1
`

type GetWeeklySubmissionParams struct {
	UserID     int64 `json:"user_id"`
	WeekNumber int32 `json:"week_number"`
	Year       int32 `json:"year"`
}

func (q *Queries) GetWeeklySubmission(ctx context.Context, arg GetWeeklySubmissionParams) (WeeklySubmission, error) {
	row := q.db.QueryRow(ctx, getWeeklySubmission, arg.UserID, arg.WeekNumber, arg.Year)
	var i WeeklySubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekNumber,
		&i.Year,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeeklySubmissionsByID = `-- name: GetWeeklySubmissionsByID :one
SELECT id, user_id, week_number, year, status, submitted_at, approved_at, processed_by, processed_at, created_at, updated_at FROM weekly_submissions WHERE id = $1
`

func (q *Queries) GetWeeklySubmissionsByID(ctx context.Context, id uuid.UUID) (WeeklySubmission, error) {
	row := q.db.QueryRow(ctx, getWeeklySubmissionsByID, id)
	var i WeeklySubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekNumber,
		&i.Year,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimeEntry = `-- name: UpdateTimeEntry :one
UPDATE time_entries
SET
    start_time = $2,
    end_time = $3,
    break_min = $4,
    duration_h = $5,
    note = $6
WHERE
    id = $1
RETURNING
    id, submission_id, entry_date, start_time, end_time, break_min, duration_h, note, created_at, updated_at
`

type UpdateTimeEntryParams struct {
	ID        uuid.UUID      `json:"id"`
	StartTime pgtype.Time    `json:"start_time"`
	EndTime   pgtype.Time    `json:"end_time"`
	BreakMin  pgtype.Int4    `json:"break_min"`
	DurationH pgtype.Numeric `json:"duration_h"`
	Note      pgtype.Text    `json:"note"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, updateTimeEntry,
		arg.ID,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMin,
		arg.DurationH,
		arg.Note,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMin,
		&i.DurationH,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWeeklySubmissionStatus = `-- name: UpdateWeeklySubmissionStatus :one
UPDATE weekly_submissions
SET
    status = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, user_id, week_number, year, status, submitted_at, approved_at, processed_by, processed_at, created_at, updated_at
`

type UpdateWeeklySubmissionStatusParams struct {
	ID     uuid.UUID            `json:"id"`
	Status SubmissionStatusEnum `json:"status"`
}

func (q *Queries) UpdateWeeklySubmissionStatus(ctx context.Context, arg UpdateWeeklySubmissionStatusParams) (WeeklySubmission, error) {
	row := q.db.QueryRow(ctx, updateWeeklySubmissionStatus, arg.ID, arg.Status)
	var i WeeklySubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekNumber,
		&i.Year,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ProcessedBy,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
