// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicUserBySessionToken = `-- name: GetPublicUserBySessionToken :one
SELECT
    id,
    first_name,
    last_name,
    email,
    role,
    team_id,
    start_date
FROM users
WHERE
    session_token = $1
LIMIT 1
`

type GetPublicUserBySessionTokenRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) GetPublicUserBySessionToken(ctx context.Context, sessionToken pgtype.Text) (GetPublicUserBySessionTokenRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserBySessionToken, sessionToken)
	var i GetPublicUserBySessionTokenRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    first_name,
    last_name,
    email,
    password_hash,
    session_token,
    csrf_token,
    role,
    team_id,
    start_date
FROM users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID           int64       `json:"id"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	SessionToken pgtype.Text `json:"session_token"`
	CsrfToken    pgtype.Text `json:"csrf_token"`
	Role         RoleEnum    `json:"role"`
	TeamID       pgtype.Int8 `json:"team_id"`
	StartDate    pgtype.Date `json:"start_date"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.SessionToken,
		&i.CsrfToken,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
	)
	return i, err
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT id, first_name, last_name, email, password_hash, session_token, csrf_token, role, team_id, start_date, created_at, updated_at
FROM users
WHERE
    session_token = $1
    AND session_token IS NOT NULL
LIMIT 1
`

func (q *Queries) GetUserBySessionToken(ctx context.Context, sessionToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.SessionToken,
		&i.CsrfToken,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTokens = `-- name: UpdateUserTokens :exec
UPDATE users
SET
    session_token = $1,
    csrf_token = $2
WHERE
    id = $3
`

type UpdateUserTokensParams struct {
	SessionToken pgtype.Text `json:"session_token"`
	CsrfToken    pgtype.Text `json:"csrf_token"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) error {
	_, err := q.db.Exec(ctx, updateUserTokens, arg.SessionToken, arg.CsrfToken, arg.ID)
	return err
}
