// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO
    teams (name, supervisor_id)
VALUES ($1, $2)
RETURNING
    id,
    name,
    supervisor_id
`

type CreateTeamParams struct {
	Name         string      `json:"name"`
	SupervisorID pgtype.Int8 `json:"supervisor_id"`
}

type CreateTeamRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	SupervisorID pgtype.Int8 `json:"supervisor_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (CreateTeamRow, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.SupervisorID)
	var i CreateTeamRow
	err := row.Scan(&i.ID, &i.Name, &i.SupervisorID)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        first_name,
        last_name,
        email,
        password_hash,
        role,
        team_id,
        start_date
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    first_name,
    last_name,
    email,
    role,
    created_at
`

type CreateUserParams struct {
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         RoleEnum    `json:"role"`
	TeamID       pgtype.Int8 `json:"team_id"`
	StartDate    pgtype.Date `json:"start_date"`
}

type CreateUserRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.TeamID,
		arg.StartDate,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllSupervisors = `-- name: GetAllSupervisors :many
SELECT id, first_name, last_name, email
FROM users
WHERE
    role = 'supervisor'
ORDER BY id
`

type GetAllSupervisorsRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
}

func (q *Queries) GetAllSupervisors(ctx context.Context) ([]GetAllSupervisorsRow, error) {
	rows, err := q.db.Query(ctx, getAllSupervisors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSupervisorsRow{}
	for rows.Next() {
		var i GetAllSupervisorsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicUserBySessionToken = `-- name: GetPublicUserBySessionToken :one
SELECT
    id,
    first_name,
    last_name,
    email,
    role,
    team_id,
    start_date
FROM users
WHERE
    session_token = $1
LIMIT 1
`

type GetPublicUserBySessionTokenRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) GetPublicUserBySessionToken(ctx context.Context, sessionToken pgtype.Text) (GetPublicUserBySessionTokenRow, error) {
	row := q.db.QueryRow(ctx, getPublicUserBySessionToken, sessionToken)
	var i GetPublicUserBySessionTokenRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT u.id, u.first_name, u.last_name, u.email, u.role, u.team_id
FROM users u
WHERE
    u.team_id = $1
ORDER BY u.id
`

type GetTeamMembersRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID pgtype.Int8) ([]GetTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamMembersRow{}
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    first_name,
    last_name,
    email,
    role,
    team_id,
    start_date,
    created_at
FROM users
WHERE
    id = $1
LIMIT 1
`

type GetUserRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    first_name,
    last_name,
    email,
    password_hash,
    session_token,
    csrf_token,
    role,
    team_id,
    start_date
FROM users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID           int64       `json:"id"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	SessionToken pgtype.Text `json:"session_token"`
	CsrfToken    pgtype.Text `json:"csrf_token"`
	Role         RoleEnum    `json:"role"`
	TeamID       pgtype.Int8 `json:"team_id"`
	StartDate    pgtype.Date `json:"start_date"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.SessionToken,
		&i.CsrfToken,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
	)
	return i, err
}

const getUserBySessionToken = `-- name: GetUserBySessionToken :one
SELECT id, first_name, last_name, email, password_hash, session_token, csrf_token, role, team_id, start_date, created_at, updated_at
FROM users
WHERE
    session_token = $1
    AND session_token IS NOT NULL
LIMIT 1
`

func (q *Queries) GetUserBySessionToken(ctx context.Context, sessionToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.SessionToken,
		&i.CsrfToken,
		&i.Role,
		&i.TeamID,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, supervisor_id FROM teams ORDER BY id
`

type ListTeamsRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	SupervisorID pgtype.Int8 `json:"supervisor_id"`
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SupervisorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsWithDetails = `-- name: ListTeamsWithDetails :many
SELECT
    t.id,
    t.name,
    t.supervisor_id,
    u.first_name as supervisor_first_name,
    u.last_name as supervisor_last_name,
    u.email as supervisor_email
FROM teams t
    LEFT JOIN users u ON t.supervisor_id = u.id
ORDER BY t.id
`

type ListTeamsWithDetailsRow struct {
	ID                  int64       `json:"id"`
	Name                string      `json:"name"`
	SupervisorID        pgtype.Int8 `json:"supervisor_id"`
	SupervisorFirstName pgtype.Text `json:"supervisor_first_name"`
	SupervisorLastName  pgtype.Text `json:"supervisor_last_name"`
	SupervisorEmail     pgtype.Text `json:"supervisor_email"`
}

func (q *Queries) ListTeamsWithDetails(ctx context.Context) ([]ListTeamsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listTeamsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsWithDetailsRow{}
	for rows.Next() {
		var i ListTeamsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SupervisorID,
			&i.SupervisorFirstName,
			&i.SupervisorLastName,
			&i.SupervisorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    first_name,
    last_name,
    email,
    role,
    team_id,
    start_date
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Role,
			&i.TeamID,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamSupervisor = `-- name: UpdateTeamSupervisor :one
UPDATE teams
SET
    supervisor_id = $2
WHERE
    id = $1
RETURNING
    id,
    name,
    supervisor_id
`

type UpdateTeamSupervisorParams struct {
	ID           int64       `json:"id"`
	SupervisorID pgtype.Int8 `json:"supervisor_id"`
}

type UpdateTeamSupervisorRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	SupervisorID pgtype.Int8 `json:"supervisor_id"`
}

func (q *Queries) UpdateTeamSupervisor(ctx context.Context, arg UpdateTeamSupervisorParams) (UpdateTeamSupervisorRow, error) {
	row := q.db.QueryRow(ctx, updateTeamSupervisor, arg.ID, arg.SupervisorID)
	var i UpdateTeamSupervisorRow
	err := row.Scan(&i.ID, &i.Name, &i.SupervisorID)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    email = COALESCE($4, email),
    role = COALESCE($5, role),
    team_id = COALESCE($6, team_id),
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id,
    first_name,
    last_name,
    email,
    role,
    updated_at
`

type UpdateUserParams struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	TeamID    pgtype.Int8 `json:"team_id"`
}

type UpdateUserRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     string      `json:"email"`
	Role      RoleEnum    `json:"role"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Role,
		arg.TeamID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $2,
    updated_at = NOW()
WHERE
    id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserTokens = `-- name: UpdateUserTokens :exec
UPDATE users
SET
    session_token = $1,
    csrf_token = $2
WHERE
    id = $3
`

type UpdateUserTokensParams struct {
	SessionToken pgtype.Text `json:"session_token"`
	CsrfToken    pgtype.Text `json:"csrf_token"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) error {
	_, err := q.db.Exec(ctx, updateUserTokens, arg.SessionToken, arg.CsrfToken, arg.ID)
	return err
}
