// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id,
  first_name,
  last_name,
  email,
  password_hash,
  session_token,
  csrf_token,
  role,
  supervisor_id,
  start_date
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64          `json:"id"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	SessionToken sql.NullString `json:"session_token"`
	CsrfToken    sql.NullString `json:"csrf_token"`
	Role         RoleEnum       `json:"role"`
	SupervisorID sql.NullInt64  `json:"supervisor_id"`
	StartDate    sql.NullTime   `json:"start_date"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.SessionToken,
		&i.CsrfToken,
		&i.Role,
		&i.SupervisorID,
		&i.StartDate,
	)
	return i, err
}
